name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  env-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

  build-components:
    runs-on: ubuntu-latest
    needs:
      - env-setup
    steps:
      - name: Build Vue Components
        run: |
          cd vue-components
          npm ci
          npm run build

  test-quality:
    runs-on: ubuntu-latest
    needs:
      - env-setup
    steps:
      - name: Install dependencies
        run: |
          python -m pip install ".[ci]"

      - name: Check pre-commit
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files

  release:
    needs:
      - build-components
      - test-quality
    runs-on: ubuntu-latest
    concurrency: release
    environment:
      name: pypi
      url: https://pypi.org/project/trame-tweakpane/
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.release.outputs.released == 'true'
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish package distributions to GitHub Releases
        uses: python-semantic-release/upload-to-gh-release@main
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

